SELECT * FROM EMPLOYEES WHERE JOB_ID IN (SELECT JOB_IDENT FROM JOBS);

SELECT * FROM EMPLOYEES WHERE JOB_ID IN (SELECT JOB_IDENT FROM JOBS WHERE JOB_TITLE='Jr. Designer');

SELECT F_NAME,SALARY, (SELECT JOB_TITLE FROM JOBS WHERE JOB_IDENT = JOB_ID) FROM EMPLOYEES WHERE SALARY>70000;
select JOB_TITLE, MIN_SALARY,MAX_SALARY,JOB_IDENT from jobs where JOB_IDENT IN (select JOB_ID from employees where SALARY > 70000 );

SELECT F_NAME,L_NAME, B_DATE, (SELECT JOB_TITLE FROM JOBS WHERE JOB_IDENT = JOB_ID) FROM EMPLOYEES WHERE YEAR(B_DATE)>1976;
select JOB_TITLE, MIN_SALARY,MAX_SALARY,JOB_IDENT from jobs where JOB_IDENT IN (select JOB_ID from employees where YEAR(B_DATE)>1976 );

SELECT JOB_TITLE, MIN_SALARY,MAX_SALARY,JOB_IDENT from JOBS where JOB_IDENT IN (select JOB_ID from employees where YEAR(B_DATE)>1976 AND SEX = 'F' );


SELECT * FROM EMPLOYEES, JOBS;

SELECT * FROM EMPLOYEES, JOBS WHERE EMPLOYEES.JOB_ID = JOBS.JOB_IDENT;

SELECT * FROM EMPLOYEES E, JOBS J WHERE E.JOB_ID = J.JOB_IDENT;

SELECT EMP_ID,F_NAME,L_NAME,JOB_TITLE FROM EMPLOYEES E, JOBS J WHERE E.JOB_ID = J.JOB_IDENT;

SELECT E.EMP_ID,E.F_NAME,E.L_NAME,J.JOB_TITLE FROM EMPLOYEES E, JOBS J WHERE E.JOB_ID = J.JOB_IDENT;