CALL RETRIEVE_ALL;      -- Caller query

DROP PROCEDURE RETRIEVE_ALL;

CALL RETRIEVE_ALL;



CALL RETRIEVE_ALL;

CALL UPDATE_SALEPRICE(1, 'BAD');        -- Caller query

CALL RETRIEVE_ALL;


CALL RETRIEVE_ALL;

CALL UPDATE_SALEPRICE(3, 'WORSE');      -- Caller query

CALL RETRIEVE_ALL;