SELECT Case_Number, Primary_Type, COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME_DATA CCD
INNER JOIN CENSUS_DATA CD ON CCD.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER	
WHERE CCD.COMMUNITY_AREA_NUMBER = '18';


SELECT Case_Number, Primary_Type, COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME_DATA CCD
LEFT OUTER JOIN CENSUS_DATA CD ON CCD.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER	
WHERE CCD.LOCATION_DESCRIPTION LIKE '%SCHOOL%';


SELECT CD.COMMUNITY_AREA_NAME, CD.COMMUNITY_AREA_NUMBER, CCD.Case_Number
FROM CHICAGO_CRIME_DATA CCD
FULL OUTER JOIN CENSUS_DATA CD ON CCD.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER	
WHERE CD.COMMUNITY_AREA_NAME IN ('Oakland', 'Armour Square', 'Edgewater', 'CHICAGO');